create table c4(
c3_index int,
c4_index int NOT NULL AUTO_INCREMENT PRIMARY KEY,
c4Code char(10),
c4NameKR char(100),
c4CoordMapX float(9,6),
c4CoordMapY float(9,6),
c4TradeCounts char(5),
c4LeaseCounts char(5),
c4RentCounts char(5),
c4ComplexNumTotalHouses varchar(1024),
c4ComplexNumHouses char(12),
c4ComplexNumLongtermRent varchar(1024),
c4ComplexNumBuildings char(12),
c4ComplexBuiltDate char(12),
c4ComplexConstructionCompany varchar(100),
c4ComplexTotalParkingLots char(12),
c4ComplexParkingLotPerHouse char(10),
c4ComplexHeatingType char(12),
c4ComplexFuelForHeat char(12),
c4ComplexFloorAreaRatio char(10),
c4ComplexCoverageRatio char(10),
c4ComplexHighestFloor char(5),
c4ComplexLowestFloor char(5),
c4ComplexAreaTypeFloatList varchar(3072),
c4ComplexAreaTypeIntList varchar(3072),
c4ComplexAdminOfficeTel char(50),
c4ComplexAddress1 char(50),
c4ComplexAddress2 char(50),
timestamp char(10),
index idx_c4_index(c4_index),
foreign key(c3_index) references c3(c3_index) on delete set null)engine=innodb;
